---

- include: section_1_management_plane.yml
  become: true
- include: section_2_control_plane.yml
  become: true
# - include: section_3_data_plane.yml
#   become: true
- include: radius.yml
  become: true

- name: Save conf
  ios_command:
    commands: write
  vars:
    ansible_command_timeout: 60
  tags:
    - section1
    - section2
    - save    