---

- name: radius_1 starts new AAA configuration
  ios_config:
    commands: 
      - aaa new-model
  when: radius
  tags:
    - radius_1
    - radius

- name: radius_2 apply radius group on dot1x
  ios_config:
    commands: 
      - aaa authentication dot1x default group radius
  when: radius
  tags:
    - radius_2
    - radius

- name: radius_3 enable 802.1x authentication globally, on the entire switch
  ios_config:
    commands: 
      - dot1x system-auth-control 
  when: radius
  tags:
    - radius_3
    - radius

- name: radius_4 select the 802.1x activation zone and activate it
  ios_config:
    parents: interface {{ interfaces_8021x }}
    lines:
      - dot1x port-control auto
  ignore_errors: yes  
  when: radius
  tags:
    - radius_4
    - radius

- name: radius_5 Conf radius server
  ios_config:
    lines: 
      - radius-server host {{ ip_radius }} auth-port {{ auth_port }} acct-port {{ acct_port }} key {{ secret_string }}
  when: radius
  tags:
    - radius_5
    - radius