---

##########################################################################################################################################################
#####################                 1.1 Local Authentication, Authorization and Accounting (AAA) Rules                             #####################
##########################################################################################################################################################

# 1.1.1 Enable 'aaa new-model' (Scored)
- name: 1.1.1 Enable 'aaa new-model'
  block:
  - name: 1.1.1 ACT Enable 'aaa new-model'
    ios_config:
      lines:
        -  "aaa new-model"
    when: not radius and not requirement
  - name: 1.1.1 Mess Control Enable 'aaa new-model'
    debug:
      msg: |
        done during requirement
    when: requirement
  tags:
    - section1
    - level_1
    - '1.1.1'
    - scored
    - '1.1'

# # 1.1.2 Enable 'aaa authentication login' (Scored)
- name: 1.1.2 Enable 'aaa authentication login'
  block:
  - name: 1.1.2 ACT Enable 'aaa authentication login'
    ios_config:
      lines:
        -  "aaa authentication login default local-case"
    when: not radius and not requirement
  - name: 1.1.2 MESS Enable 'aaa authentication login'
    debug:
      msg: |
        done during requirement
    when: requirement
  tags:
    - section1
    - level_1
    - '1.1.2'
    - scored
    - '1.1'

# # 1.1.3 Enable 'aaa authentication enable default' (Scored)
- name: 1.1.3 Enable 'aaa authentication enable default'
  block:
  - name: 1.1.3 ACT Enable 'aaa authentication enable default'
    ios_config:
      lines:
        -  "aaa authentication enable default enable"
    when: not radius and not requirement
  - name: 1.1.3 MESS Enable 'aaa authentication enable default'
    debug:
      msg: |
        done during requirement
    when: requirement
  tags:
    - section1
    - level_1
    - '1.1.3'
    - scored
    - '1.1'

# # 1.1.4 Set 'login authentication for 'line con 0' (Scored)
- name: 1.1.4 Set 'login authentication for 'line con 0'
  ios_config:
    lines:
      - "line console 0"
      - "login authentication default"
  tags:
    - section1
    - level_1
    - '1.1.4'
    - scored
    - '1.1'

# # 1.1.5 Set 'login authentication for 'line tty' (Scored)
- name: 1.1.5 Set 'login authentication for 'line tty'
  ios_config:
    lines:
      - "line tty 0 4"
      - "login authentication default"
  when: tty
  tags:
    - section1
    - level_1
    - '1.1.5'
    - scored
    - '1.1'

# # 1.1.6 Set 'login authentication for 'line vty' (Scored)
- name: 1.1.6 Set 'login authentication for 'line vty'
  ios_config:
    lines:
      - "login authentication default"
    parents: line vty 0 4      
  tags:
    - section1
    - level_1
    - '1.1.6'
    - scored
    - '1.1'

# # 1.1.7 Set 'aaa accounting' to log all privileged use commands using 'commands 15' (Scored)
- name: 1.1.7 Set 'aaa accounting' to log all privileged use commands using 'commands 15'
  block:
  - name: 1.1.7 ACT Set 'aaa accounting' to log all privileged use commands using 'commands 15'
    ios_config:
      lines:
        -  "aaa authorization commands 15 default local"
    when: not radius and not requirement
  - name: 1.1.7 MESS Set 'aaa accounting' to log all privileged use commands using 'commands 15'
    debug:
      msg: |
        done during requirement
    when: requirement  
  tags:
    - section1
    - level_2
    - '1.1.7'
    - scored
    - '1.1'

# 1.1.8 Set 'aaa accounting connection' (Scored)
- name: 1.1.8 Set 'aaa accounting connection'
  ios_config:
    lines:
      - "aaa accounting connection default"
  when: not radius
  tags:
    - section1
    - level_2
    - 1.1.8
    - scored

# 1.1.9 Set 'aaa accounting exec' (Scored)
- name: 1.1.9 Set 'aaa accounting exec'
  ios_config:
    lines:
      - "aaa accounting exec default"
  when: not radius
  tags:
    - section1
    - level_2
    - 1.1.9
    - scored

# 1.1.10 Set 'aaa accounting network' (Scored)
- name: 1.1.10 Set 'aaa accounting network'
  ios_config:
    lines:
      - "aaa accounting network default"
  when: not radius
  tags:
    - section1
    - level_2
    - 1.1.10
    - scored

# 1.1.11 Set 'aaa accounting system' (Scored)
- name: 1.1.11 Set 'aaa accounting system'
  ios_config:
    lines:
      - "aaa accounting system default"
  when: not radius
  tags:
    - section1
    - level_2
    - 1.1.11
    - scored

##########################################################################################################################################################
#####################                                                  1.2 Access Rules                                              #####################
##########################################################################################################################################################

# 1.2.1 Set 'privilege 1' for local users (Scored)
- name: 1.2.1 Set 'privilege 1' for local users
  ios_config:
    lines:
      - "username {{ USER_PRIV_1 }} privilege 1 "
  tags:
    - section1
    - level_1
    - '1.2.1'
    - scored 
    - '1.2'

# 1.2.2 Set 'transport input ssh' for 'line vty' connections (Scored)
- name: 1.2.2 MANUAL Set 'transport input ssh' for 'line vty' connections
  ios_config:
    lines:
      -  transport input ssh
    parents: line vty 0 4
  tags:
    - section1
    - level_1
    - '1.2.2'
    - scored 
    - '1.2'

# 1.2.3 Set 'no exec' for 'line aux 0' (Scored)
- name: 1.2.3 Set 'no exec' for 'line aux 0'
  ios_config:
    lines:
      - "no exec"
    parents: line aux 0
  when: device == 'router'
  tags:
    - section1
    - level_1
    - '1.2.3'
    - scored 
    - '1.2'

# 1.2.4 Create 'access-list' for use with 'line vty' (Not Scored)
- name: 1.2.4 Create 'access-list' for use with 'line vty' 
  ios_config:
    lines:
      - access-list {{ vty_acl_number_vty }} permit {{ vty_acl_addr_vty }} {{ vty_acl_mask_vty }} 
  tags:
    - section1
    - level_1
    - '1.2.4'
    - not_scored 
    - '1.2'


# - name: 1.2.4 Create 'access-list' for use with 'line vty' 
#   ios_acls:
#     config:
#     - afi: ipv4
#       acls:
#       - name: 1 #"{{ vty_acl_number }}"
#         acl_type: standard
#         aces:
#         - grant: permit
#           protocol_options:
#               tcp:
#                 ack: true
#           source:
#             address:  0.0.0.0 #"{{ vty_acl_host }}"
#             wildcard_bits: 255.255.255.255 #"{{ vty_acl_block_with_mask }}"
#     state: merged
#   tags:
#     - section1
#     - level_1
#     - '1.2.4'
#     - not_scored 
#     - '1.2'

# 1.2.5 Set 'access-class' for 'line vty' (Scored)
- name: 1.2.5 MANUAL Set 'access-class' for 'line vty'
  ios_config:
    lines:
      -  "access-class {{ vty_acl_number }} in"
    parents: line vty 0 4
  tags:
    - section1
    - level_1
    - '1.2.5'
    - scored 
    - '1.2'

# 1.2.6 Set 'exec-timeout' to less than or equal to 10 minutes for 'line aux 0' (Scored)
- name: 1.2.6 Set 'exec-timeout' to less than or equal to 10 minutes for 'line aux 0'
  ios_config:
    lines:
      - "exec-timeout {{ timeout_aux }}"
    parents: line aux 0
  when: device == 'router'
  tags:
    - section1
    - level_1
    - '1.2.6'
    - scored 
    - '1.2'

# 1.2.7 Set 'exec-timeout' to less than or equal to 10 minutes for 'line console 0' (Scored)
- name: 1.2.7 Set 'exec-timeout' to less than or equal to 10 minutes for 'line console 0'
  ios_config:
    lines:
      - "exec-timeout {{ timeout_con }}"
    parents: line con 0
  tags:
    - section1
    - level_1
    - '1.2.7'
    - scored 
    - '1.2'

# 1.2.8 Set 'exec-timeout' less than or equal to 10 minutes 'line tty' (Scored)
- name: 1.2.8 Set 'exec-timeout' less than or equal to 10 minutes 'line tty'
  ios_config:
    lines:
      - "exec-timeout {{ timeout_tty }}"
    parents: line tty 0 4
  when: tty
  tags:
    - section1
    - level_1
    - '1.2.8'
    - scored 
    - '1.2'

# 1.2.9 Set 'exec-timeout' to less than or equal to 10 minutes 'line vty' (Scored)
- name: 1.2.9 Set 'exec-timeout' to less than or equal to 10 minutes 'line vty'
  ios_config:
    lines:
      - "exec-timeout {{ timeout_vty }}"
    parents: line vty 0 4
  tags:
    - section1
    - level_1
    - '1.2.9'
    - scored 
    - '1.2'

# 1.2.10 Set 'transport input none' for 'line aux 0' (Scored)
- name: 1.2.10 Set 'transport input none' for 'line aux 0'
  ios_config:
    lines:
      - "transport input none"
    parents: line aux 0
  when: device == 'router'
  tags:
    - section1
    - level_1
    - '1.2.10'
    - scored 
    - '1.2'

##########################################################################################################################################################
#####################                                                  1.3 Banner Rules                                              #####################
##########################################################################################################################################################

# 1.3.1 Set the 'banner-text' for 'banner exec' (Scored)
- name: 1.3.1 Set the 'banner-text' for 'banner exec'
  ios_banner:
    banner: exec
    text: |
      *** Ensure that you update the system configuration ***
      *** documentation after making system changes.      ***
    state: present
  tags:
    - section1
    - level_1
    - '1.3.1'
    - scored
    - '1.3'

# 1.3.2 Set the 'banner-text' for 'banner login' (Scored)
- name: 1.3.2 Set the 'banner-text' for 'banner login'
  ios_banner:
    banner: login
    text: |
      *** Login Required. Unauthorized use is prohibited ***
    state: present
  tags:
    - section1
    - level_1
    - '1.3.2'
    - scored
    - '1.3'

# 1.3.3 Set the 'banner-text' for 'banner motd' (Scored)
- name: 1.3.3 Set the 'banner-text' for 'banner motd'
  ios_banner:
    banner: motd
    text: |
      This device is for authorized personnel only. 
      If you have not been provided with permission to access this device - disconnect at once.
    state: present
  tags:
    - section1
    - level_1
    - '1.3.3'
    - scored  
    - '1.3'

##########################################################################################################################################################
#####################                                                  1.4 Password Rules                                            #####################
##########################################################################################################################################################

# 1.4.1 Set 'password' for 'enable secret' (Scored)
- name: 1.4.1 Set 'password' for 'enable secret'
  block:
  - name: 1.4.1 CTRL Set 'password' for 'enable secret'
    ios_command:
      commands:
        - sh run | incl enable secret     
    register: test
  - name: 1.1.1 Mess Control Enable 'aaa new-model'
    debug:
      msg: |
        fait lors de la phase des pre-requis {{ test.stdout_lines }}
  tags:
    - section1
    - level_1
    - '1.4.1'
    - scored  
    - '1.4'

# 1.4.2 Enable 'service password-encryption' (Scored)
- name: 1.4.2 Enable 'service password-encryption'
  ios_config:
    lines:
      -  "service password-encryption"
  tags:
    - section1
    - level_1
    - '1.4.2'
    - scored  
    - '1.4'

# 1.4.3 Set 'username secret' for all local users (Scored)
- name: 1.4.3 Set 'username secret' for all local users
  block:
  - name: 1.4.3 CTRL Set 'username secret' for all local users
    ios_command:
      commands:
        - show run | incl username   
    register: test
  - name: 1.4.3 MESS Set 'username secret' for all local users
    debug:
      msg: |
        fait lors de la phase des pre-requis {{ test.stdout_lines }}
  tags:
    - section1
    - level_1
    - '1.4.3'
    - scored  
    - '1.4'

##########################################################################################################################################################
#####################                                                  1.5 SNMP Rules                                                #####################
##########################################################################################################################################################

# 1.5.1 Set 'no snmp-server' to disable SNMP when unused (Scored)
- name: 1.5.1 Set 'no snmp-server' to disable SNMP when unused
  ios_config:
    lines:
      - no snmp-server
  when:
  - not need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.1'
    - scored  
    - '1.5'

# 1.5.2 Unset 'private' for 'snmp-server community' (Scored)
- name: 1.5.2 Unset 'private' for 'snmp-server community'
  ios_config:
    lines:
      - no snmp-server community {{ private }}
  when:
  - not need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.2'
    - scored  
    - '1.5'

# 1.5.3 Unset 'public' for 'snmp-server community' (Scored)
- name: 1.5.3 Unset 'public' for 'snmp-server community'
  ios_config:
    lines:
      - no snmp-server community {{ public }}
  when:
  - not need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.3'
    - scored  
    - '1.5'


# 1.5.4 Do not set 'RW' for any 'snmp-server community' (Scored)
- name: 1.5.4 Unset 'RW' for 'snmp-server community'
  ios_config:
    lines:
      - no snmp-server community {{ write_community_string }}
  when:
  - not need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.4'
    - scored  
    - '1.5'    

# 1.5.5 Set the ACL for each 'snmp-server community' (Scored)
- name: 1.5.5 Set the ACL for each 'snmp-server community'
  ios_config:
    lines:
      - snmp-server community  {{ community_string }} ro {{ snmp_access-list_name }}
  when:
  - need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.5'
    - scored  
    - '1.5'       

# 1.5.6 Create an 'access-list' for use with SNMP (Scored)
- name: 1.5.6 Create an 'access-list' for use with SNMP
  ios_config:
    lines:
      - access-list {{ snmp_acl_number }} permit {{ snmp_access-list }}
      - access-list deny any log
  when:
  - need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.6'
    - scored  
    - '1.5'  

# 1.5.7 Set 'snmp-server host' when using SNMP (Scored)
- name: 1.5.7 Set 'snmp-server host' when using SNMP
  ios_config:
    lines:
      - snmp-server host {{ snmp_server_ip }} {{ trap_community_string }} snmp
  when:
  - need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.7'
    - scored  
    - '1.5'  

# 1.5.8 Set 'snmp-server enable traps snmp' (Scored)
- name: 1.5.8 Set 'snmp-server enable traps snmp'
  ios_config:
    lines:
      - snmp-server enable traps snmp authentication linkup linkdown coldstart
  when:
  - need_SNMP
  tags:
    - section1
    - level_1
    - '1.5.8'
    - scored  
    - '1.5'   

# 1.5.9 Set 'priv' for each 'snmp-server group' using SNMPv3 (Scored)
- name: 1.5.9 Set 'priv' for each 'snmp-server group' using SNMPv3
  ios_config:
    lines:
      - snmp-server group {{ group_name }} v3 priv
  when:
  - need_SNMP
  tags:
    - section1
    - level_2
    - '1.5.9'
    - scored  
    - '1.5'    

# 1.5.10 Require 'aes 128' as minimum for 'snmp-server user' when using SNMPv3 (Scored)
- name: 1.5.10 Require 'aes 128' as minimum for 'snmp-server user' when using SNMPv3
  ios_config:
    lines:
      - snmp-server user {{ user_name }} {{ group_name }} v3 encrypted auth sha {{ auth_password }} priv aes 128 {{ priv_password }} {{ acl_name }}
  when:
  - need_SNMP
  tags:
    - section1
    - level_2
    - '1.5.10'
    - scored  
    - '1.5'    
          